
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 24 17:27:49 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 28;
  public static final int RBPAR = 15;
  public static final int READ = 4;
  public static final int LT = 22;
  public static final int SEMICOLON = 13;
  public static final int PLUS = 18;
  public static final int OR = 29;
  public static final int FSLASH = 21;
  public static final int INT = 6;
  public static final int LTE = 23;
  public static final int CHAR = 7;
  public static final int WHILE = 2;
  public static final int INTCONST = 31;
  public static final int LBPAR = 14;
  public static final int GT = 26;
  public static final int COLON = 16;
  public static final int ID = 30;
  public static final int GTE = 27;
  public static final int WRITE = 5;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int REALCONST = 33;
  public static final int CHARCONST = 32;
  public static final int MAIN = 3;
  public static final int ASTER = 20;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int EQ = 24;
  public static final int ASSIGN = 12;
  public static final int BOOL = 9;
  public static final int RPAR = 11;
  public static final int REAL = 8;
  public static final int NEQ = 25;
  public static final int LPAR = 10;
  public static final int BOOLCONST = 34;
}

