
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 16 01:45:27 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 2;
  public static final int LPAR = 3;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int ID = 4;
  public static final int ASSIGN = 6;
  public static final int error = 1;
  public static final int SEMICOLON = 7;
  public static final int RPAR = 5;
  public static final int CONST = 9;
}

