
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 21 14:25:12 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 30;
  public static final int RBPAR = 14;
  public static final int READ = 11;
  public static final int LT = 24;
  public static final int SEMICOLON = 7;
  public static final int PLUS = 8;
  public static final int OR = 31;
  public static final int FSLASH = 23;
  public static final int INT = 17;
  public static final int LTE = 25;
  public static final int CHAR = 18;
  public static final int WHILE = 2;
  public static final int LBPAR = 13;
  public static final int GT = 28;
  public static final int COLON = 15;
  public static final int GTE = 29;
  public static final int WRITE = 12;
  public static final int ID = 4;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int MAIN = 10;
  public static final int ASTER = 22;
  public static final int MINUS = 21;
  public static final int CONST = 9;
  public static final int error = 1;
  public static final int EQ = 26;
  public static final int ASSIGN = 6;
  public static final int BOOL = 20;
  public static final int RPAR = 5;
  public static final int REAL = 19;
  public static final int NEQ = 27;
  public static final int LPAR = 3;
}

