
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 28 14:29:30 CET 2014
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 21;
  public static final int RBPAR = 11;
  public static final int LT = 22;
  public static final int SEMICOLON = 13;
  public static final int PLUS = 16;
  public static final int OR = 20;
  public static final int FSLASH = 19;
  public static final int INT = 3;
  public static final int CHAR = 4;
  public static final int WHILE = 7;
  public static final int INTCONST = 26;
  public static final int LBPAR = 10;
  public static final int GT = 24;
  public static final int COLON = 12;
  public static final int ID = 25;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int REALCONST = 28;
  public static final int CHARCONST = 27;
  public static final int MAIN = 2;
  public static final int ASTER = 18;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int EQ = 23;
  public static final int ASSIGN = 15;
  public static final int BOOL = 6;
  public static final int RPAR = 9;
  public static final int REAL = 5;
  public static final int LPAR = 8;
  public static final int BOOLCONST = 29;
}

